--------------------------------------------------
--Tablas
--------------------------------------------------

CREATE TABLE APPLICATION
(
  APPLICATIONID  NUMBER(38)                     NOT NULL,
  NAME           VARCHAR2(50 BYTE)              NOT NULL
);


CREATE TABLE ENTITY
(
  ENTITYID         NUMBER(38)                   NOT NULL,
  APPLICATIONID    NUMBER(38)                   NOT NULL,
  NAME             VARCHAR2(50 BYTE)            NOT NULL,
  TABLENAMEPREFIX  VARCHAR2(50 BYTE)            NOT NULL
);


CREATE TABLE ENTITYINSTANCE
(
  ENTITYINSTANCEID  NUMBER(38)                  NOT NULL,
  ENTITYID          NUMBER(38)                  NOT NULL,
  KEYINFO           VARCHAR2(200 BYTE)          NOT NULL
);


CREATE TABLE ENTITYPROPERTY
(
  ENTITYID  NUMBER(38)                          NOT NULL,
  ISKEY     NUMBER(1)                           NOT NULL,
  SEQUENCE  NUMBER(5)                           NOT NULL,
  NAME      VARCHAR2(50 BYTE)                   NOT NULL
);


CREATE UNIQUE INDEX APPLICATION_UK ON APPLICATION
(NAME);


CREATE UNIQUE INDEX APPLICATION_PK ON APPLICATION
(APPLICATIONID);


CREATE UNIQUE INDEX ENTITY_PK ON ENTITY
(ENTITYID);


CREATE UNIQUE INDEX ENTITY_UK ON ENTITY
(APPLICATIONID, NAME);


CREATE UNIQUE INDEX ENTITYINSTANCE_PK ON ENTITYINSTANCE
(ENTITYINSTANCEID);


CREATE UNIQUE INDEX ENTITYINSTANCE_UK ON ENTITYINSTANCE
(ENTITYID, KEYINFO);


CREATE UNIQUE INDEX ENTITYPROPERTY_PK ON ENTITYPROPERTY
(ENTITYID, ISKEY, SEQUENCE);


CREATE TABLE ENTITYHISTORY
(
  ENTITYINSTANCEID  NUMBER(38)                  NOT NULL,
  DATEMODIFIED      DATE                        NOT NULL,
  ACTION            NUMBER(5)                   NOT NULL,
  USERNAME          VARCHAR2(50 BYTE)           NOT NULL,
  DATAINFO          VARCHAR2(4000 BYTE)
);


CREATE UNIQUE INDEX ENTITYHISTORY_PK ON ENTITYHISTORY
(ENTITYINSTANCEID, DATEMODIFIED);


ALTER TABLE APPLICATION ADD (
  CONSTRAINT APPLICATION_PK
 PRIMARY KEY
 (APPLICATIONID));


ALTER TABLE ENTITY ADD (
  CONSTRAINT ENTITY_PK
 PRIMARY KEY
 (ENTITYID));


ALTER TABLE ENTITYINSTANCE ADD (
  CONSTRAINT ENTITYINSTANCE_PK
 PRIMARY KEY
 (ENTITYINSTANCEID));


ALTER TABLE ENTITYPROPERTY ADD (
  CONSTRAINT ENTITYPROPERTY_PK
 PRIMARY KEY
 (ENTITYID, ISKEY, SEQUENCE));


ALTER TABLE ENTITYHISTORY ADD (
  CONSTRAINT ENTITYHISTORY_C01
 CHECK (ACTION BETWEEN 1 AND 3));

ALTER TABLE ENTITYHISTORY ADD (
  CONSTRAINT ENTITYHISTORY_PK
 PRIMARY KEY
 (ENTITYINSTANCEID, DATEMODIFIED));


ALTER TABLE ENTITY ADD (
  CONSTRAINT ENTITY_R01 
 FOREIGN KEY (APPLICATIONID) 
 REFERENCES APPLICATION (APPLICATIONID));


ALTER TABLE ENTITYINSTANCE ADD (
  CONSTRAINT ENTITYINSTANCE_R01 
 FOREIGN KEY (ENTITYID) 
 REFERENCES ENTITY (ENTITYID));


ALTER TABLE ENTITYPROPERTY ADD (
  CONSTRAINT ENTITYPROPERTY_R01 
 FOREIGN KEY (ENTITYID) 
 REFERENCES ENTITY (ENTITYID));


ALTER TABLE ENTITYHISTORY ADD (
  CONSTRAINT ENTITYHISTORY_R01 
 FOREIGN KEY (ENTITYINSTANCEID) 
 REFERENCES ENTITYINSTANCE (ENTITYINSTANCEID));
 
--------------------------------------------------
--Secuencias 
--------------------------------------------------


CREATE SEQUENCE APPLICATION_ID_SEQ
  START WITH 0
  MAXVALUE 999999999999999999999999999
  MINVALUE 0
  NOCYCLE
  NOCACHE
  NOORDER;


CREATE SEQUENCE ENTITYINSTANCE_ID_SEQ
  START WITH 3
  MAXVALUE 999999999999999999999999999
  MINVALUE 0
  NOCYCLE
  NOCACHE
  NOORDER;


CREATE SEQUENCE ENTITY_ID_SEQ
  START WITH 0
  MAXVALUE 999999999999999999999999999
  MINVALUE 0
  NOCYCLE
  NOCACHE
  NOORDER;
 
 
